### ISSUE TITLE
Applicability to other data types?

### ISSUE THREAD

**Issue by 83years** [ebecht/infinityFlow#1]
Hi, 

This isn't an issue per se, but more of a question of the data that can be used as input. 

I have two cytometry panels with directly seven overlapping parameters (e.g CD4 BB790 on both panels) and four overlapping markers (e.g panel 1: CD56 on PE and panel 2: CD56 BV421). Is it possible to impute the 7-9 non-overlapping markers onto a new panel using this tool? 

If so, what input would I need for the Isotypes (which weren't run), can there be more than one exploratory channel per run? 

Many thanks,
Lucas

**Comment by ebecht** [comment]
Hi Lucas,

While similar approaches can be used to merge panel, this software is not designed to do so.

Maybe you could try [CyTOFmerge](https://github.com/tabdelaal/CyTOFmerge)? I think it would work fine on flow cytometry data.

Best,
Etienne

**Comment by 83years** [comment]
Hi Etienne,

Thanks for the link...I’ll try that first. 

My thinking was that the non-linear learning method would allow for less noisy results than a clustering method. 

Best,

Lucas

**Comment by ebecht** [comment]
Hi Lucas,

You're totally right that non-linear regression will give potentially more granular results than clustering methods.

If I'm not mistaken, CyTOFmerge also uses non-linear regression, by using k-nearest neighbor regression.

It should apply to your use case!

Cheers,
Etienne

**Comment by ebecht** [comment]
Hi @83years 

Bit old of an issue now but better late than never. I've packaged a function to merge arbitrary partially-overlapping cytometry panels here : [cytoMerge](https://github.com/ebecht/cytoMerge). Maybe it can still be useful to you. I haven't tested it in-depth.

It will merge independent FCS files based on overlapping "name" parameters. Please let me know if you need more details!

Best,
Etienne
