### ISSUE TITLE
infinity_flow error 

### ISSUE THREAD

**Issue by SmithMaxine** [ebecht/infinityFlow#10]
Hi,

I was running the infinity flow pipeline, but I keep getting an error message. 

I did the sample data and it all worked perfectly. I chose to put 10 FCS files to ensure it would work on my data, the backbone code runs perfectly. When I try running infinity_flow, it gets down to # Exporting results, and then I get the following error; 

Error in data.frame(file = unique_pes, target = a[unique_pes], PE_id = seq_len(length(unique_pes))) : 
  row names contain missing values

Any help would be appreciated, thank you. 

Max

**Comment by ebecht** [comment]
Hi Max,

This sounds like a problem with the annotation file.

Could you check that `all(names(annotation) %in% list.files(path_to_fcs))` and `all(names(isotype) %in% list.files(path_to_fcs))` ?

If you want to test the software on your data, you can also include all the files and input `input_events_downsampling = 1000` and `prediction_events_downsampling = 100`, it should then run fairly quickly !

Hopefully this helps,
Etienne

**Comment by SmithMaxine** [comment]
Hi Etienne, 

It was a problem with my annotation file! 
Everything is now running fine.

Thank you for your help!
Maxine

**Comment by ebecht** [comment]
Hi Maxime,

Great, I am glad to hear this.

I will close this issue but feel free to open another one if you encounter any other problem !
Etienne
