### ISSUE TITLE
How to check the accuracy of logicle transformation before proceeding with infinity_flow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ebecht/infinityFlow#18]
Hi there, 

Thank you again for the package. 

A reviewer asked to confirm whether we checked whether the logicle transformation was done accurately by visualizing the marker expressions on density map for example. 

But, the way the `infinity_flow()` function is written, there is not an intermediate step to check this accuracy. 

Would you mind advising me how we coud still check this potential issue? 

Thank you for your help.

Related to issue #6.

**Comment by ebecht** [comment]
Hello,

If you used a non-default `path_to_intermediary_results` argument, that folder will contain an `rds` subfolder which contains a file called `xp_transformed.rds`. This contains the logicle-transformed data for all events in matrix format. Maybe you could use it to plot histograms and make sure the transformed data distribution looks satisfactory ?

Wish you the best for your revision

**Comment by denvercal1234GitHub** [comment]
Thank you again very much, @ebecht.

For visualization, likely just the transformed, but is there a case when we should use the `xp_transformed_scaled.Rds` instead of the `xp_transformed.Rds`?
