### ISSUE TITLE
Warning: Some data values of 'CD49E.LASSO2' channel exceed its $PnR value 175864747 and will be truncated!  To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ebecht/infinityFlow#20]
Hi there, 

Thanks again for the package. 

During the Exporting results, I encountered a Warning as below for almost all markers even though I used `PeacoQC::RemoveMargin` to filter out events greater than 2e+06 before running `infinityFlow`. My data was acquired by spectral cytek Aurora.

Do you usually set `truncate_max_range = FALSE` in this scenareo? If so, how might I do so as the `infinity_flow` is just one function?

The argument `extra_args_read_FCS` is for reading in input but I did not find analogous argument for the output FCS.

Thank you for your help.

<img width="1237" alt="Screenshot 2023-03-06 at 23 13 59" src="https://user-images.githubusercontent.com/62179082/223278004-d810fa12-a062-47f1-939b-9ebdde7b13d6.png">

<img width="1233" alt="Screenshot 2023-03-06 at 23 14 44" src="https://user-images.githubusercontent.com/62179082/223278113-97ccea66-45bf-48c5-a411-36406620833a.png">

**Comment by ebecht** [comment]
Hi,

I think R shows warnings at the end of the function call so I would still expect these warnings to be produced by data import. Which is weird because based on the name of the parameters, these appear to have already been produced by regression models. So I am a bit confused about what is going on here ! Any additional details you could share?

Thanks,
Etienne

**Comment by denvercal1234GitHub** [comment]
Hi @ebecht - These warnings were produced after the function `infinity_flow()`. My input data to infinity_flow() was untransformed FCS files that have been undergone `PeacoQC::RemoveMargins()` with `minRange = -Inf, maxRange = 2000000` for all channels (except Time and FSC, and SSC).

I used fluorescence-minus-PE as "Blank" for Isotype. 

This line `all(names(TRIAL21_F37_annotation) %in% list.files(path_to_fcs))` returned `FALSE` but `all(names(isotypes) %in% list.files(path_to_fcs))` returned `TRUE`

In the backbone specificiation file, I "discard" FJComp-AF-A -- do you do this too?

I used XGBoost, SVM, LASSO2, and LM.

Below is the code:

```
TRIAL_fcs_data <- read.flowSet(path=".../FCS_trial", pattern="*.fcs", transformation = FALSE, truncate_max_range = FALSE)

channels <- c("FJComp-AF-A", 
              "FJComp-AF594-A", 
              "FJComp-APC-A",
              "FJComp-APC-Fire 750-A", "FJComp-PE-A",...)

channelSpecs <- list(
              "FJComp-AF-A" = c(minRange = -Inf, maxRange = 2000000), 
              "FJComp-AF594-A"= c(minRange = -Inf, maxRange = 2000000), ...), 
"FJComp-PE-A"= c(minRange = -Inf, maxRange = 2000000),...)

TRIAL_fcs_data_RemovedMargin <- list()

for (i in 1:length(TRIAL_fcs_data)){
    TRIAL_fcs_data_RemovedMargin[[i]] <- PeacoQC::RemoveMargins(ff=TRIAL_fcs_data[[i]], channels=channels, channel_specifications = channelSpecs, output="frame")
    names(F37_CD4CD8DP_Untransformed_TRIAL_fcs_data_RemovedMargin)[i] <- F37_CD4CD8DP_Untransformed_TRIAL_fcs_data[[i]]@description$`$FIL`
    }

## Optional converting a list to flowSet for using FlowViz 
TRIAL_fcs_data_RemovedMargin_fs <- flowCore::as(TRIAL_fcs_data_RemovedMargin, "flowSet")
```


**My annotation file** 
<img width="738" alt="Screenshot 2023-03-08 at 11 13 57" src="https://user-images.githubusercontent.com/62179082/223698961-ac04ff7b-bd7c-4974-ae66-321711cd77d7.png">

**My backbone specification** 
<img width="648" alt="Screenshot 2023-03-08 at 11 15 21" src="https://user-images.githubusercontent.com/62179082/223699269-73a710f9-de1a-4210-851a-a5d5f29afc36.png">
<img width="641" alt="Screenshot 2023-03-08 at 11 16 07" src="https://user-images.githubusercontent.com/62179082/223699434-d6e811c7-8ce1-4fb5-96ee-49c6f62536c6.png">
<img width="647" alt="Screenshot 2023-03-08 at 11 16 17" src="https://user-images.githubusercontent.com/62179082/223699475-c71f6aa4-c51d-491d-915e-12eb725e634d.png">


```
regression_functions <- list(
    XGBoost = fitter_xgboost, # XGBoost
## Passed to fitter_nn, e.g. neural networks through keras::fit. See https://keras.rstudio.com/articles/tutorial_basic_regression.html
#NN = fitter_nn,
    SVM = fitter_svm, # SVM
    LASSO2 = fitter_glmnet, # L1-penalized 2nd degree polynomial model
    LM = fitter_linear # Linear model
)


backbone_size <- table(read.csv(TRIAL21_backbone_selection_file)[,"type"])["backbone"]
backbone_size


extra_args_regression_params <- list(
  
    list(nrounds = 500, eta = 0.05),

    list(type = "nu-regression", cost = 8, nu=0.5, kernel="radial"),

    list(alpha = 1, nfolds=10, degree = 2),

    list(degree = 1)
)



if(length(regression_functions) != length(extra_args_regression_params)){
    stop("Number of models and number of lists of hyperparameters mismatch")
}

imputed_data <- infinity_flow(
	regression_functions = regression_functions,
	extra_args_regression_params = extra_args_regression_params,
	path_to_fcs = "..../FCS_trial",
	path_to_output = "..../TRIAL_21FCS/output",
	path_to_intermediary_results = "..../TRIAL_21FCS/tmp",
	backbone_selection_file = TRIAL21_backbone_selection_file,
	annotation = targets,
	isotype = "Blank",
	input_events_downsampling = Inf, 
	prediction_events_downsampling = 1000
	verbose = TRUE,
	#Note: there is an issue with serialization of the neural networks and socketing since I updated to R-4.0.1. If you want to use neural networks, please make sure to set cores = 1L
	cores = cores,
	neural_networks_seed = NULL
)
```

**Comment by denvercal1234GitHub** [comment]
Definitely, the input FCS do not have any channels with `.LASS02`. 

Would it be okay and not too inconvenient to you if I shared with you 3 FCS files via email to test the code above?

**Comment by denvercal1234GitHub** [comment]
Hi @ebecht -- From `flowCore` it looks like it was issues with `PnR` and data truncation that happened in the `read.FCS` instead of `write.FCS` (https://github.com/RGLab/flowCore/issues/169). 

I am still unsure how to proceed, nevertheless. 

Would it be helpful and not too inconvenient to you if I shared with you some FCS files via email to troubleshoot?

**Comment by denvercal1234GitHub** [comment]
Interestingly, when I checked the codes of `infinity_flow()` (https://github.com/ebecht/infinityFlow/blob/master/R/00_master.R), line 16 indicates that the `truncate_max_range` was already set to `FALSE` when reading FCS into `inifnity_flow()`?

**Comment by ebecht** [comment]
Hi @denvercal1234GitHub 

As I was suggesting in my first reply, this warning sounds indeed like it is produced by `flowCore::read.FCS`. The only places where this happens in the code is when input data is read (see [here](https://github.com/ebecht/infinityFlow/blob/master/R/01_infinity_flow_fcs_parsing.R)). These input files **should not** have a channel called something.LASSO2.

As for models, we showed in our paper that LASSO2 (2nd degree polynomial models) were quite bad in this context and shouldn't be used. In general we recommended XGBoost. SVMs, NNs and XGBoost give overall very similar results so it does not matter much which one you choose.

**Comment by denvercal1234GitHub** [comment]
Thanks @ebecht for your response. That is very strange because indeed my input file does not have any channel called something.LASSO2, but `infinity_flow` still threw this warning. Yet, the warning only happens when `input_events_downsampling <- Inf`and did not happen when `input_events_downsampling <- 2000` for example.

**Comment by ebecht** [comment]
That is likely because when you use 2000 events you randomly get rid out of the problematic ones.

In any case, I'd encourage you to not use linear and polynomial models which we have shown to be less accurate, so if the warnings are not produced by the other models I think you can safely ignore them.
