### ISSUE TITLE
Question about backbone selection and error in dimnames(x)

### ISSUE THREAD

**Issue by GRT-coder** [ebecht/infinityFlow#8]
Hello, first of all, thank you for this very helpful pipeline and vignettes. 

1. I have preliminar data from a LegendScreen assay from Biolegend. I didn't acquire the files and all of them are annotated in the PE channel with its corresponding target (PE-A::CD1a), when I run the select_backbone_and_exploratory_markers() I can see in the description "CD1a" (which is the first fcs file marker). The tutorial is annotated with "Legend" in all samples for the PE channel, since is the exploratory target. Does is this a problem? Should I change this description in all my samples from CD1a, CD1b, etc. to Legend?

2. I followed the tutorial without any error, when I try to do it with my samples I keep rising the same error:
` Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent`

I don't know if second issue might be related to my first one or if it is something totally different.  Apart from that everything is much the same as the tutorial. 

Regards.

**Comment by denvercal1234GitHub** [comment]
@GRT-coder - Would you mind letting us know what you found out about your questions 1 and 2?
