### ISSUE TITLE
error in annotation and Isotype argument

### ISSUE THREAD

**Issue by yaozhan2022** [ebecht/infinityFlow#9]
Hi,

I was running the infinity flow pipeline, but keeps getting error messages. Wondering could you please give some advise? Thank you!

imputed_data <- infinity_flow(
  path_to_fcs = '/path/to/fcs/files', #input_dir,
  path_to_output = path_to_output,
  path_to_intermediary_results = path_to_intermediary_results,
  backbone_selection_file = backbone_specification,
  annotation = targets,
  isotype = isotypes,
  input_events_downsampling = 2000,#input_events_downsampling,
  prediction_events_downsampling = 500,#prediction_events_downsampling,
  verbose = TRUE,
  cores = cores
)

 The following values from the isotype argument are not matching any of the values from the annotation argument: NA, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG1, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, mouse IgG2a, k, 

[File.annotation_ENG-001.csv](https://github.com/ebecht/infinityFlow/files/10048961/File.annotation_ENG-001.csv)

**Comment by yaozhan2022** [comment]
fixed. thanks

**Comment by Sandyna** [comment]
But... How? I have the same problem
